name: flutter_range_slider
description: a 2-thumb Material Design range slider for Flutter that allows a range selection
version: 1.3.1
author: Didier Boelens <mail@didierboelens.com>
homepage: https://github.com/boeledi/RangeSlider

environment:
    sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
